# Generated by Django 2.1.7 on 2019-04-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название книги')),
                ('series', models.CharField(max_length=120, verbose_name='Серия')),
                ('number', models.CharField(max_length=120, verbose_name='Номер')),
            ],
        ),
    ]
