# Generated by Django 2.2 on 2019-04-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190409_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='author',
        ),
        migrations.AddField(
            model_name='products',
            name='author',
            field=models.ManyToManyField(related_name='products', to='products.Author', verbose_name='Автор(ы)'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='genre',
        ),
        migrations.AddField(
            model_name='products',
            name='genre',
            field=models.ManyToManyField(related_name='products', to='products.Genre', verbose_name='Жанр(ы)'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Обложка'),
        ),
    ]
