# Generated by Django 2.2 on 2019-04-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190412_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing', models.CharField(max_length=120, verbose_name='Издательство')),
            ],
            options={
                'verbose_name': 'Издательство',
            },
        ),
        migrations.RemoveField(
            model_name='products',
            name='publishing',
        ),
        migrations.AddField(
            model_name='products',
            name='publishing',
            field=models.ManyToManyField(related_name='products', to='products.Publishing', verbose_name='Издательство'),
        ),
    ]
