# Generated by Django 2.2 on 2019-04-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190412_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='publishing',
        ),
        migrations.AddField(
            model_name='products',
            name='publishing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.Publishing', verbose_name='Издательство'),
            preserve_default=False,
        ),
    ]
