# Generated by Django 2.2 on 2019-04-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190412_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='city',
            field=models.CharField(default=1, max_length=40, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
