# Generated by Django 2.2 on 2019-04-12 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_publishing_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author',
            new_name='name',
        ),
    ]
