# Generated by Django 2.1.7 on 2019-04-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=120, verbose_name='Жанр')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='name_a',
            field=models.CharField(default=1, max_length=140, verbose_name='Автор(ы)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название книги'),
        ),
    ]
