# Generated by Django 2.1.7 on 2019-04-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publishing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название книги')),
                ('year', models.CharField(max_length=4, verbose_name='Год издания')),
                ('city', models.CharField(max_length=40, verbose_name='Город')),
                ('who', models.CharField(max_length=140, verbose_name='Издательство')),
            ],
        ),
    ]
