# Generated by Django 2.1.7 on 2019-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishing',
            name='kuku',
            field=models.CharField(default=2, max_length=40, verbose_name='kuku'),
            preserve_default=False,
        ),
    ]
