# Generated by Django 2.1.7 on 2019-04-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_publishing_kuku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publishing',
            name='kuku',
        ),
    ]
